---
apiVersion: v1
kind: Pod
metadata:
  name: pavan-pod-label1
  labels:
    app: nginx
    env: dev
    release: v1.1
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP



apiVersion: v1
kind: Pod
metadata:
  name: pavan-pod-label2
  labels:
    app: nginx
    env: dev
    release: v1.1
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP          

apiVersion: v1
kind: Pod
metadata:
  name: pavan-pod-label3
  labels:
    app: nginx
    env: dev
    release: v1.1
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP                    