---
apiVersion: v1
kind: Pod
metadata:
  name: yash-pod
  label:
    app: nginx
    env: dev
    release: v1.1
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP

    - name: jenkins
      image: jenkins/jenkins:jdk17
      ports:
        - containerPort: 8080
          protocol: TCP      
